#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    start_server                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mstratu <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/30 14:59:15 by mstratu           #+#    #+#              #
#    Updated: 2019/09/30 14:59:15 by mstratu          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Run the teamspeak server

export LD_LIBRARY_PATH=/opt/teamspeak
cd /opt/teamspeak
./ts3server logpath=/data/logs


